### ISSUE TITLE
SimpleLogin domains marked in your disposable emails list

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [wesbos/burner-email-providers#414]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that one of our domains is present your list of disposable emails. To be more precise, we are referring to slmail.me. 

Could we trouble you to please clarify why this is the case? Would it be possible to correct this?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by emh-rowland-oconnor** [comment]
Hi Nikola.

Thank you for reaching out.

These domains are on the list because the on-boarding process for ProtonMail permits anonymous signup.

**Comment by Nikola-Test-for-Proton** [comment]
Hello,

Thank you for following up.

Could you please elaborate further? 

Please note that when creating a Proton account, one has the option to verify via different means, including by utilizing email verification and/or via a phone number. We are privacy-focused, but do not advertise ourselves as being anonymous. 

Keep in mind that we take Anti-Abuse and Anti-Spam very seriously at Proton and have a number of mechanisms in place to ensure against registration-, phishing-, and spam-related abuse. If you have any concrete examples you'd like for us to review, we'd be more than happy to oblige. 

Looking forward to your response.

**Comment by emh-rowland-oconnor** [comment]
Just signed up to proton.me anonymously using the following workflow:

- https://account.proton.me/mail/signup?plan=free&billing=12&minimumCycle=12&currency=EUR&ref=prctbl
- Username: xxxx, password: xxxx
- Create Account ->
- Verification: Slide the jigsaw piece into place
- Recovery methods: skip
- Into the mailbox that now allows full send / receive capability

At no stage was I asked to provide personally identifiable information to verify my identity from another vector (e.g. phone number).

The lack of human verification stage means that anyone can register for protonmail for any reason at any time - such as creating email accounts that are temporary (i.e. disposable) with the intent of using the email address to sign up to 3rd party sites.

As there is zero friction in identifying a person before provisioning a fully working email address, protonmail is vulnerable to easy exploitation by individuals seeking to secure temporary/disposable email address resources. This is why it is in the disposable list.

Hope this helps clarify the rationale behind including protonmail on the list.

Of course it is the right for individuals to use anonymous email boxes such as protonmail. It is also the right for 3rd party services to be aware of anonymous email addresses so that appropriate risk analysis can occur.

**Comment by Nikola-Test-for-Proton** [comment]
Hello,

Thank you for following up.

Please note that verifying via Captcha is also an option we have.

This was introduced in light of problems in restrictive countries, where human verification using your phone number and/or email address is not feasible. Using the latter two options should, however, have been available to you. 

Keep in mind that, as pointed out in our previous message, we do have anti-abuse and anti-spam mechanisms in place that safeguard against the sort of problems you've mentioned. In case you (or any third-party service) have a concrete example, we would appreciate it if you could let us know so our team can review and attune our system in an adequate manner.

**Comment by Ufyfughx** [comment]
In this case you should block:

(no verification)
skiff.com 
tutanota.com
tutanota.de
tutamail.com
tuta.io
keemail.me


anonaddy.com
anonaddy.me

anonaddy.com and anonaddy.me are the same of SimpleLogin.

If you are blocking such services then block all. Or unblock SimpleLogin because now it is kind of discrimination.

**Comment by Ufyfughx** [comment]
@emh-rowland-oconnor

**Comment by emh-rowland-oconnor** [comment]
@ghost 
Agreed and point taken on the discrimination issue. Will stick in a PR in due course.

Just one note on these lists of burner email providers. It is that these lists are not "blocking" anything. The lists exist to allow for visibility of domains that might present concern for certain 3rd party use cases (e.g. such as onboarding trial accounts). It is the decision of whomever consumes these lists whether or not to implement "blocking" or other such risk mitigation measures.

**Comment by knubew** [comment]
`It is the decision of whomever consumes these lists whether or not to implement "blocking" or other such risk mitigation measures.`
That's right, you nailed it. Thanks.

**Comment by ctdyfyv** [comment]
> Agreed and point taken on the discrimination issue. Will stick in a PR in due course.

@Nikola-Test-for-Proton please create it :)

**Comment by ctdyfyv** [comment]
> Agreed and point taken on the discrimination issue. Will stick in a PR in due course.

@Nikola-Test-for-Proton please create it :)

**Comment by ctdyfyv** [comment]
> Agreed and point taken on the discrimination issue. Will stick in a PR in due course.

I created PR https://github.com/wesbos/burner-email-providers/pull/417

@emh-rowland-oconnor and @Nikola-Test-for-Proton

**Comment by Bob3178** [comment]
> `It is the decision of whomever consumes these lists whether or not to implement "blocking" or other such risk mitigation measures.` That's right, you nailed it. Thanks.

But many services BLOCKS such mails based in this lists…

**Comment by knubew** [comment]
> > `It is the decision of whomever consumes these lists whether or not to implement "blocking" or other such risk mitigation measures.` That's right, you nailed it. Thanks.
> 
> But many services BLOCKS such mails based in this lists…

Anyone who uses the list has the opportunity to initially check the list for their use and add or remove domains as needed. With the help of the PRs, every user can then easily evaluate the domains that have been added and either adopt them or not. Ultimately, the users of this list are always responsible. The users who shy away from a bit of work and are too lazy to maintain the list for their own needs have themselves to blame.

**Comment by yrahul3910** [comment]
> > > `It is the decision of whomever consumes these lists whether or not to implement "blocking" or other such risk mitigation measures.` That's right, you nailed it. Thanks.
> 
> > 
> 
> > But many services BLOCKS such mails based in this lists…
> 
> 
> 
> Anyone who uses the list has the opportunity to initially check the list for their use and add or remove domains as needed. With the help of the PRs, every user can then easily evaluate the domains that have been added and either adopt them or not. Ultimately, the users of this list are always responsible. The users who shy away from a bit of work and are too lazy to maintain the list for their own needs have themselves to blame.

How many users of this will actually do that, and do you have data supporting this? By this logic you should add GMail, iCloud Private Relay, and Outlook which can all be abused to create burner email accounts, since the users of this library can always remove them, correct?

**Comment by michalgolab** [comment]
@knubew, @emh-rowland-oconnor 

I'm a little late for the show, and moreover, it might be challenging for you to grasp the ideas I'm expressing because they delve into the realm of philosophy, but I'll try anyway.

Everyone is responsible for their creations, whether it's a book, a movie, a device, or a child. The more the surface of the world (the lives of others, the environment, etc.) is affected by the creation, the more accountable the creator becomes. Failure to recognize this indicates short-sightedness, and intentionally ignoring it is at least an act of selfishness. The manifestation of this responsibility can be observed in various aspects of our lives.

For instance, security researchers typically refrain from publishing their discoveries to the public, they are not arguing that it is the user's responsibility to use exploits wisely. Instead, they contact the creator of the affected thing (software or hardware), and provide a reasonable timeframe to address the flaw. Another example is seemingly trivial, such as the warnings on coffee cups in fast-food restaurants stating, "Caution! Handle with care. I'm hot." In some countries, individuals can even be held accountable for the dissemination of dangerous ideas, like fascism, where the propagator, not the receptor, assumes responsibility.

Throughout human history, numerous examples of carelessness in this regard can be found, from food products to weaponry and spying software. It's time to learn from these examples and apply the lesson to even seemingly simple and meaningless things like a filtering list. The responsibility lies on both parties - the user and the creator.

**Comment by RokeJulianLockhart** [comment]
https://github.com/wesbos/burner-email-providers/issues/422#issue-2014732132
